### ISSUE TITLE
[FE] LOGIN

### ISSUE THREAD

**Issue by K0ruru** [Nexthrive/NexademyV2WEB#1]

**Comment by K0ruru** [comment]
i did it :) 
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/1a733c1c-81bc-4a8d-ad96-a76cd79321f0" />

**Comment by cey0** [comment]
bukan admin jing. ganti employee

**Comment by K0ruru** [comment]
Udah akuh ganti mas
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/86e44f2f-b002-40dd-afca-881fe30329d3" />

**Comment by cey0** [comment]
dibilang bukan admin jing

**Comment by K0ruru** [comment]
Iyah mangapp hehe :)

<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/0aded56e-2db4-488f-a1ca-1a2e7edcbac8" />

**Comment by cey0** [comment]
ganti text nya jelek

**Comment by K0ruru** [comment]
UDAH BANG
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/a46beb89-703d-46dc-a075-a72537e1f3c6" />

**Comment by cey0** [comment]
mantap
